DROP TABLE IF EXISTS executions_new;
DROP TABLE IF EXISTS _operations_backup;
DROP TABLE IF EXISTS _usage_blocks_backup;
DROP TABLE IF EXISTS _execution_logs_backup;
CREATE TABLE _operations_backup (execution_id TEXT NOT NULL, name TEXT NOT NULL, position INTEGER NOT NULL, status TEXT NOT NULL, started_at TEXT NOT NULL, completed_at TEXT, result_json TEXT, error_json TEXT, PRIMARY KEY(execution_id, name));
INSERT OR IGNORE INTO _operations_backup (execution_id, name, position, status, started_at, completed_at, result_json, error_json) SELECT execution_id, name, position, status, started_at, completed_at, result_json, error_json FROM operations;
CREATE TABLE _usage_blocks_backup (execution_id TEXT PRIMARY KEY, usage_json TEXT NOT NULL, created_at TEXT NOT NULL);
INSERT OR IGNORE INTO _usage_blocks_backup (execution_id, usage_json, created_at) SELECT execution_id, usage_json, created_at FROM usage_blocks;
CREATE TABLE _execution_logs_backup (seq INTEGER PRIMARY KEY, execution_id TEXT NOT NULL, org_id TEXT NOT NULL, user_id TEXT NOT NULL, saga_id TEXT NOT NULL, saga_name TEXT NOT NULL, level TEXT NOT NULL, message TEXT NOT NULL, data_json TEXT, created_at TEXT NOT NULL);
INSERT OR IGNORE INTO _execution_logs_backup (seq, execution_id, org_id, user_id, saga_id, saga_name, level, message, data_json, created_at) SELECT seq, execution_id, org_id, user_id, saga_id, saga_name, level, message, data_json, created_at FROM execution_logs;
DROP TABLE IF EXISTS operations;
DROP TABLE IF EXISTS usage_blocks;
DROP TABLE IF EXISTS execution_logs;
CREATE TABLE executions_new (id TEXT PRIMARY KEY, saga_id TEXT NOT NULL, saga_name TEXT NOT NULL, saga_revision TEXT NOT NULL, org_id TEXT NOT NULL, user_id TEXT NOT NULL, input_json TEXT NOT NULL CHECK(length(input_json) <= 4096), dispatched INTEGER NOT NULL DEFAULT 0 CHECK(dispatched IN (0, 1)), status TEXT NOT NULL DEFAULT 'Pending' CHECK(status IN ('Pending', 'Running', 'Succeeded', 'Failed', 'TimedOut', 'Cancelling', 'Cancelled')), created_at TEXT NOT NULL, started_at TEXT, completed_at TEXT, result_json TEXT CHECK(result_json IS NULL OR length(result_json) <= 4096), error_json TEXT, policy_json TEXT, parent_execution_id TEXT, parent_step TEXT);
INSERT INTO executions_new (id, saga_id, saga_name, saga_revision, org_id, user_id, input_json, dispatched, status, created_at, started_at, completed_at, result_json, error_json, policy_json, parent_execution_id, parent_step) SELECT id, saga_id, saga_name, saga_revision, org_id, user_id, input_json, dispatched, status, created_at, started_at, completed_at, result_json, error_json, policy_json, parent_execution_id, parent_step FROM executions;
DROP TABLE executions;
ALTER TABLE executions_new RENAME TO executions;
CREATE TABLE operations (execution_id TEXT NOT NULL REFERENCES executions(id), name TEXT NOT NULL, position INTEGER NOT NULL CHECK(position >= 0), status TEXT NOT NULL CHECK(status IN ('Running', 'Succeeded', 'Failed')), started_at TEXT NOT NULL, completed_at TEXT, result_json TEXT CHECK(result_json IS NULL OR length(result_json) <= 4096), error_json TEXT, PRIMARY KEY(execution_id, name));
INSERT OR IGNORE INTO operations (execution_id, name, position, status, started_at, completed_at, result_json, error_json) SELECT execution_id, name, position, status, started_at, completed_at, result_json, error_json FROM _operations_backup;
CREATE TABLE usage_blocks (execution_id TEXT PRIMARY KEY REFERENCES executions(id), usage_json TEXT NOT NULL CHECK(length(usage_json) <= 4096), created_at TEXT NOT NULL);
INSERT OR IGNORE INTO usage_blocks (execution_id, usage_json, created_at) SELECT execution_id, usage_json, created_at FROM _usage_blocks_backup;
CREATE TABLE execution_logs (seq INTEGER PRIMARY KEY AUTOINCREMENT, execution_id TEXT NOT NULL REFERENCES executions(id), org_id TEXT NOT NULL REFERENCES organizations(id), user_id TEXT NOT NULL, saga_id TEXT NOT NULL, saga_name TEXT NOT NULL, level TEXT NOT NULL CHECK(level IN ('DEBUG','INFO','WARN','ERROR','PROGRESS')), message TEXT NOT NULL CHECK(length(message) BETWEEN 1 AND 1024), data_json TEXT CHECK(data_json IS NULL OR length(data_json) <= 2048), created_at TEXT NOT NULL);
INSERT OR IGNORE INTO execution_logs (seq, execution_id, org_id, user_id, saga_id, saga_name, level, message, data_json, created_at) SELECT seq, execution_id, org_id, user_id, saga_id, saga_name, level, message, data_json, created_at FROM _execution_logs_backup;
DROP TABLE IF EXISTS _operations_backup;
DROP TABLE IF EXISTS _usage_blocks_backup;
DROP TABLE IF EXISTS _execution_logs_backup;
CREATE INDEX IF NOT EXISTS executions_history ON executions(org_id, user_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS executions_parent ON executions(parent_execution_id);
CREATE INDEX IF NOT EXISTS execution_logs_tail ON execution_logs(execution_id, seq ASC);
CREATE INDEX IF NOT EXISTS execution_logs_search ON execution_logs(org_id, user_id, created_at ASC, seq ASC);
